### PR TITLE
update package deps to exclude internal lib. 

### LINKED ISSUE #1: can't npm install
There are dependencies that reference internal projects. We need to strip them out or bring the relevant ones into the organizational repo.

specifically `ja-client-dot-engine`

### PR DESCRIPTION
**Pull request by naveedn**
update npm scripts. add contributer info as well. 

Resolves #1

### CODE REVIEW

**Comment by naveedn** [comment]
@rwwagner90

**Comment by RobbieTheWagner** [comment]
@naveedn do we not need our custom dot version? Not sure if anything was different

**Comment by naveedn** [comment]
Definitely not for the open-source version. The project can't compile without it anyway. I also think that the custom version of the lib is used in another project.

**Comment by RobbieTheWagner** [comment]
@naveedn what is different in our custom version?

**Pull request merged**
