### PR TITLE
Fixes caret position issue

### PR DESCRIPTION
**Pull request by tashoecraft**

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
Looks like Travis is jacked 😞

**Comment by RobbieTheWagner** [comment]
`dist` should be ignored, as well, as Travis should push the new dist as part of the build

**Comment by SRSaddler** [comment]
Approve

**Comment by SRSaddler** [comment]
Approved

**Comment by SRSaddler** [comment]
approve

**Comment by SRSaddler** [comment]
approved

**Pull request merged**
