### PR TITLE
Pill list

### PR DESCRIPTION
**Pull request by RobbieTheWagner**

### CODE REVIEW

**Comment by mfbrown** [comment]
Approved. Looks good to me.

[Approved with PullApprove](https://pullapprove.com/jibeinc/juice/pull-request/35/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=jibeinc/juice)

**Comment by SRSaddler** [comment]
good

**Comment by SRSaddler** [comment]
Approved. Looks good to me.

[Approved with PullApprove](https://pullapprove.com/jibeinc/juice/pull-request/35/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=jibeinc/juice)

**Comment by SRSaddler** [comment]
Approved. Looks good to me.

[Approved with PullApprove](https://pullapprove.com/jibeinc/juice/pull-request/35/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=jibeinc/juice)

**Comment by SRSaddler** [comment]
approved

**Pull request merged**
